name: Npm Publish

on:
  push:
    tags:
     - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: yarn
      - run: yarn build
      - run: yarn reflect
      - run: yarn isclean
      - run: yarn lint
      - run: yarn prettier
      - run: yarn test
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          dry-run: true # TODO remove this when feeling confident
